### ISSUE TITLE
Kd5 pro

### ISSUE THREAD

**Issue by Felixhosp** [goldshellminer/firmware#82]
Hola tengo un kd5 pro y el firmware 2.2 veo que aquí está la versión para kd5 2.3 pero no indica que sea para el kd5 pro me podrían decir si esa sería para mí minero? Gracias

**Comment by goldshellminer** [comment]
Hey, we don't release new firmware for KD5Pro, the one firmware 2.2.3 is for KD5, instead of KD5Pro. The firmware does not work on your miner.

In this situation, pls contact the support team and ask for flash progress, they will guide you on how to flash the miner: https://goldshellhelp.zendesk.com/hc/en-us/requests/new
