### ISSUE TITLE
CKBOX 2 Firmware upgrde not working

### ISSUE THREAD

**Issue by pitmaster2002** [goldshellminer/firmware#84]
I have a CKBOX 2 and the new firmware 2.2.6 does not work on the unit.  I tried to upgrade from 2.2.0 to 2.2.1 and so on and still does not work.

**Comment by goldshellminer** [comment]
Hey, we don't release new firmware for CKBOX II, the one firmware 2.2.6/2.2.1/2.2.0 is for **CKBOX**, instead of CKBOX 2.
**You can't upgrade CKBOX firmware on your BOX II, it does not work.** 

In this situation, pls reset the miner first. If still not working, contact support team and ask for flash progress, they will guide you on how to flash the miner: https://goldshellhelp.zendesk.com/hc/en-us/requests/new
